name: RRMEDNWT
on:
  workflow_dispatch:

jobs:
  build:
    name: Start
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect$LiteManager
        run: cmd /c show.bat

      - name:Counter
        run: cmd /c loop.bat
